marvel_stuff/models.py
from enum import unique
from flask_sqlalchemy import SQLAlchemy
import uuid
import secrets
from datetime import datetime 
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, UserMixin
from flask_marshmallow import Marshmallow

login_manager = LoginManager()
ma = Marshmallow()
@login_manager.user_loader
def load_user(user_id): #when someone logs in
    return User.query.get(user_id) #query data for that id

db = SQLAlchemy()

class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key= True, unique = True)
    email = db.Column(db.String(150), unique = True, nullable= False)
    password = db.Column(db.String, nullable = False)
    token = db.Column(db.String, nullable = False, unique=True)
    date_created = db.Column(db.DateTime, default = datetime.utcnow)
    marvel = db.relationship('Marvel', backref = 'owner', lazy = True) #every person does nesscary have a relationship with marvel

    def __init__(self, email, password, token = '', id=''):
        self.id = self.set_id()
        self.email = email
        self.password = self.set_password(password)
        self.token = self.get_token(24)

    def set_id(self):
        return str(uuid.uuid4()) #look at self.id

    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash

    def get_token(self, length):
        return secrets.token_hex(length)

#class for marvel table
class Marvel(db.Model):
    id = db.Column(db.String, primary_key= True, unique = True)
    name = db.Column(db.String, nullable= False)
    powers = db.Column(db.String, nullable = True)
    traits = db.Column(db.String, nullable = True)
    user_token = db.Column(db.String, db.ForeignKey('user.token'), nullable = False) #user.token

    def __init__(self, name, powers, traits, user_token, id= ''):
        self.id = self.set_id()
        self.name = name
        self.powers = powers
        self.traits = traits
        self.user_token = user_token

    def set_id(self):
        return str(uuid.uuid4())

# model in flash (class inpython)
class MarvelSchema(ma.Schema):
    class Meta:
        fields = ['id', 'name', 'powers', 'traits', 'user_token']

#Create a singular data point return
marvel_schema = MarvelSchema()

#Create mutiple data point return
marvel_schema = MarvelSchema(many=True)
    

marvel_stuff/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email

class UserLoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit_button = SubmitField() 

marvel_stuff/__init__.py
from flask import Flask
from config import Config
from .authentication.routes import auth
from .site.routes import site
from .api.routes import api 
from .models import db, User, login_manager, ma
from flask_migrate import Migrate
from flask_cors import CORS
from .helpers import JSONEncoder


app = Flask(__name__)

app.config.from_object(Config)
db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
login_manager.login_view = 'auth.signin'
#user must sign in inorder to access this route


migrate = Migrate(app, db)
app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)
CORS(app)

app.json_encoder = JSONEncoder

marvel_stuff/api/routes.py
from flask import Blueprint, jsonify, request, url_for
from marvel_stuff.helpers import token_required
from marvel_stuff.models import Marvel, marvel_schema

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/tester')
def getrando():
    return {'CodingTemple': 'rules'}


@api.route('/marvel', methods= ['POST'])
@token_required
def create_marvel(current_user_token):
    song = Marvel.query.get(id)
    name = request.json['name']
    powers = request.json['powers']
    traits = request.json['traits']
    user_token = current_user_token

    marvel= Marvel(name, powers, traits, user_token=user_token)

    db.session.add(marvel)
    db.session.commit()


    response = marvel_schema.dump(marvel)
    return jsonify(response)

@api.route('/marvel', methods= ['GET'])
@token_required
def get_marvel(current_user_token):
    owner = current_user_token.token
    marvel = Marvel.query.filter_by(user_token =owner).all()
    response = marvel_schema.dump(marvel)
    return jsonify(response)

@api.route('/marvel/<id>', methods= ['GET'])
@token_required
def get_marvel(current_user_token, id):
    marvel = Marvel.query.get(id)
    if marvel:
        response = marvel_schema.dump(marvel)
        return jsonify(response)
    else:
        return jsonify({'message':"That song does not exist pal.."})

@api.route('/marvel/<id>', methods= ['POST'])
@token_required
def create_marvel(current_user_token):
    song = Marvel.query.get(id)
    if song:
        song.name = request.json['name']
        song.powers = request.json['powers']
        song.traits = request.json['traits']
        song.user_token = current_user_token
    
    db.session.commit()


    response = marvel_schema.dump(marvel)
    return jsonify(response)
else:
    jsonify({'message': 'That song does not exist pal'})

@api.route('/marvel/<id>', methods= ['GET'])
@token_required
def get_marvel(current_user_token, id):
    marvel = Marvel.query.get(id)
    if marvel:
        db.session.delete(marvel)
        db.session.commit()
        response = marvel_schema.dump(marvel)
        return jsonify(response)
    else:
        return jsonify({'message':"That song does not exist pal.."})

marvel_stuff/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from marvel_stuff.forms import UserLoginForm
from marvel_stuff.models import db, User, check_password_hash
from flask_login import login_user, logout_user, login_required

auth = Blueprint('auth',__name__, template_folder='auth_templates')

@auth.route('/signup', methods=['GET','POST'])
def signup():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)
        new_user = User(email, password)
        db.session.add(new_user)
        db.session.commit()
        flash(f'You have created an account for {email}', 'auth-success')
        redirect(url_for('auth.signin'))
    return render_template('signup.html', form = form)  #render html template


@auth.route('/signin', methods=['GET','POST'])
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)
        logged_user = User.query.filter(User.email == email).first() #query my entire database and give me a list of people
        if logged_user and check_password_hash(logged_user.password, password): #do you exist in my database is that a correct email?
            login_user(logged_user)
            flash(f'Logged in as {email}', 'auth-success')
            return redirect(url_for('site.home'))
        else:
            flash('Incorrect email/password. Please try again. ', 'auth-fail')
            return redirect(url_for('auth.signin'))
    return render_template('signin.html', form = form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash(f'Successfully logged out', 'auth-success')
    return redirect(url_for('site.home'))

marvel_stuff/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site',__name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html') #render html template


@site.route('/profile')
def profile():
    return render_template('profile.html')

marvel_stuff/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<title>Marvel Charater API </title>
</head>
<body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('site.home') }}">Marvel API</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('site.home') }}">Home</a>
              </li>
              {% if current_user.is_authenticated %}

              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('site.profile') }}">Profile</a>
              </li>

              {% endif %}
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  User Portal
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  {% if not current_user.is_authenticated %}
                  <li><a class="dropdown-item" href="{{ url_for('auth.signup') }}">Sign Up</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('auth.signin') }}">Sign In</a></li>
                  {% else %}
                  <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Log Out</a></li>
                  {% endif %}
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    {% block content %}

    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

marvel_stuff/templates/form.html
<div class="row">
    <div class="col-md-5 offset-2">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                <fieldset>
                    {{ form.email.label }}<!--expecting form to pass through in routes-->
                    {{ form.email(class = "form-control", placeholder = "Enter email address") }}
                </fieldset>
                <fieldset>
                    {{ form.password.label }}
                    {{ form.password(class = "form-control", placeholder = "Enter password") }}
                </fieldset>
                    {{ form.submit_button(class = "btn btn-dark") }}
            </div>
        </form>

    </div>
</div>

marvel_stuff/templates/profile.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Welcome to the MARVEL API {{ current_user.email }}!</h1>
        <h3>Here are your credentials:</h3>
        <ul class="list-group">
            <li class="list-group-item">Email: {{ current_user.email }}</li>
            <li class="list-group-item">Token: {{ current_user.token }}</li>
        </ul>
    </div>
{% endblock content %}